### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Violet0Phoenix** [p4535992/foundryvtt-pointer#1]
pvp - pointer and pings v2.6.0

Sorry I'm just not going to put in the rest of the stuff it's too much for me to handle at the moment

I just literally cannot access any of the custom options Anytime I try it resets or crashes
I cannot put in a custom name I cannot use any of the settings All I can do is add and delete Everything else just won't work

So basically
Naiman will not work
Chains and rotation or anything of the Sword The custom menu crashes and everything frees up
Nothing will save Even if I do change something it won't save

**Comment by p4535992** [comment]
The ticket is invalid, no screenshot is been passed ... I don't have that much free time to review code without a clue
