### ISSUE TITLE
Cannot save settings[BUG]

### ISSUE THREAD

**Issue by notgithub111** [p4535992/foundryvtt-pointer#3]
**Module Version:** v2.6.0
Foundry 11.315

**Describe the bug**
The settings do not save no matter what I do.
if I attempt to add a scale adjustment to the default pointer hand, the display window stays stuck on a pointer hand, even when I select a different pointer

**To Reproduce**
1. with all default settings, if I select nothing the pointer hand is the default selection
2. adjust the scale slider to the right to max scale 3
3. Do anything else and scale setting is lost (click on "ping round" then click back and "pointer hand" is back to scale 1 default)
You can also add a 1 to the name box (from 'pointer hand' to 'pointer hand1' and 'pointer hand1' shows up in the console, but the settings are gone and the box instantly displays 'pointer hand' again, the console shows 'pointer hand1' but the UI instantly returns to 'pointer hand'
5. **No error appears in the console** when this happens, it simply ignores any changes I made
6. you can also create a new name using the "+create new" button, this makes a new pointer named 'new'
This new pointer does not save any settings, you cannot change the name or scale or anything else, if you click in the name window it change back to new instantly with no error in console

I can get an error if I take the default pointer hand and click 'scale' under animations, then I get the error in the screen shot
<img width="466" alt="pointer error" src="https://github.com/p4535992/foundryvtt-pointer/assets/62436630/84621282-2bc0-4634-91d4-dbe5f22a8dec">

**Expected behavior**
The settings should get saved but as soon as you click anything else, the settings you changed are lost, name, scale, yoyo, etc...

**Screenshots**

**Browser:**
native foundry, chrome Version 122.0.6261.113 (Official Build) (64-bit), firefox 124.0.2 (64-bit)

**Foundry Version:** 
11.315

**Game System:** 
savage worlds

**Additional context**
Add any other context (like other modules installed) about the problem here.
<img width="519" alt="foundry modules" src="https://github.com/p4535992/foundryvtt-pointer/assets/62436630/4dd056fe-37ec-4e36-87d9-9d9650f12762">

**Comment by notgithub111** [comment]
Same is try of the 'ping' key on the 'general' tab, if I change it from 'left click' to P
as soon as I click out of the text input box it reverts to 'left click'
this includes clicking somewhere else on the control box or click on the "yes" button

**Comment by exanimomeo** [comment]
It appears to be an issue in the pointer.js file, where a null pointer exception is encountered when saving the "easing" method. This issue is system agnostic. confirmed to exist on [D&D5e]
![image](https://github.com/p4535992/foundryvtt-pointer/assets/35613107/00db7222-9fdf-427d-8099-714dfebeffe4)

**Comment by p4535992** [comment]
Any PR is welcome!
This module is abandoned at least for me as in version 12 they redid a completely new api and I would have to rewrite the module almost from scratch. To those who may be interested there is an open committee in the league server to update and keep the project alive.
