### ISSUE TITLE
Update module to V12

### ISSUE THREAD

**Issue by r-valyar** [p4535992/foundryvtt-pointer#4]
Would it be possible to update the module to support v12? I don't see any bugs, just the label shows as unsupported.

**Comment by p4535992** [comment]
Is work ? KK I can update the module.json ! i'll try tonight.

**Comment by r-valyar** [comment]
I don't see errors in the console and the two main functions I use - show via X button and move view via right-click are perfectly fine :D

**Comment by r-valyar** [comment]
Looks good, I don't see console errors, everything works as expected. I think we are good to go and close this :)
